from __future__ import annotations

from datetime import date
from typing import Optional

from pydantic import Field

from .common import CanonicalModel, Location, Phenotype
from .enums import ABOGroup, BankCategory, Component

# Provenance guidance for BloodBank (set by the loader):
#   bank_id               → DERIVED   (our stable token, assigned by us, not from source)
#   source_serial         → PROVIDED  (the file's "Sr No" integer)
#   name, state, district → PROVIDED
#   location              → PROVIDED  (when coord_valid=True); SYNTHETIC (when coord_valid=False and we geocode)
#   coord_valid           → DERIVED   (computed from the raw lat/lon values)
#   address, pincode,
#   contact, category,
#   does_components,
#   service_hours         → PROVIDED  (directly from the source columns)
#   units                 → SYNTHETIC (no real inventory exists in our data; generated by SyntheticSource)
#
# Provenance guidance for InventoryUnit:
#   all fields            → SYNTHETIC  (no source contains unit-level inventory)


class InventoryUnit(CanonicalModel):
    """A single unit of blood product held at a blood bank."""

    component: Component
    abo: ABOGroup
    rh_d: bool
    phenotype_tags: Optional[Phenotype] = None
    collection_date: date
    expiry_date: date
    # Typical values: "ok" | "degraded" | "quarantined"
    storage_status: str


class BloodBank(CanonicalModel):
    # Stable token we assign (DERIVED); not the source's sequential integer.
    bank_id: str
    # The original "Sr No" from the source file (PROVIDED).
    source_serial: int
    name: str
    location: Location
    # False when the raw lat/lon was 0, null, or outside India's bounds.
    coord_valid: bool
    address: Optional[str] = None
    state: str
    district: Optional[str] = None
    pincode: Optional[str] = None
    # Single contact field: Mobile coalesced with Contact No.
    contact: Optional[str] = None
    category: Optional[BankCategory] = None
    # True ↔ source "Blood Component Available" == "YES".
    does_components: bool
    service_hours: Optional[str] = None
    units: list[InventoryUnit] = Field(default_factory=list)
